/** Short recall cues from occupational duties. These remain questions, not evidence. */
export function recallWording(statement: string): string | null {
  const pairs: Array<[RegExp, string]> = [
    [/^Analyze user needs and software requirements/i, "Analyzed user needs and software requirements"],
    [/^Develop or direct software system testing or validation/i, "Developed software tests and validation procedures"],
    [/^Modify existing software to correct errors/i, "Updated software to fix errors or improve performance"],
    [/^Prepare reports or correspondence concerning project specifications/i, "Prepared reports on project requirements and progress"],
    [/^Analyze information to determine, recommend, and plan installation/i, "Evaluated requirements for a new system or system changes"],
    [/^Store, retrieve, and manipulate data for analysis of system capabilities/i, "Prepared data to assess system capabilities and requirements"],
    [/^Design, develop and modify software systems/i, "Designed software systems using models to assess behavior"],
    [/^Determine system performance standards/i, "Established software performance requirements"],
    [/^Confer with systems analysts, engineers, programmers/i, "Coordinated system requirements with project collaborators"],
    [/^Consult with customers or other departments on project status/i, "Coordinated with users on project progress and technical issues"],
    [/^Confer with data processing or project managers/i, "Identified data-processing requirements and constraints"],
    [/^Design, build, or maintain Web sites/i, "Built and maintained websites"],
    [/^Perform Web site tests according/i, "Tested websites after updates"],
    [/^Perform or direct Web site updates/i, "Updated website content and features"],
    [/^Back up files from Web sites/i, "Created website backups for recovery"],
    [/^Recommend and implement performance improvements/i, "Implemented website performance improvements"],
    [/^Analyze user needs to determine technical requirements/i, "Analyzed user needs to define technical requirements"],
    [/^Customize insurance programs to suit individual customers/i, "Matched insurance coverage to customers' needs"],
    [/^Sell various types of insurance policies/i, "Sold insurance policies to individuals or businesses"],
    [/^Explain features, advantages, and disadvantages of various policies/i, "Explained policy features and tradeoffs to prospective customers"],
    [/^Perform administrative tasks, such as maintaining records and handling policy renewals/i, "Maintained policy records and processed renewals"],
    [/^Seek out new clients and develop clientele by networking/i, "Identified prospective customers through networking"],
    [/^Call on policyholders to deliver and explain policy/i, "Reviewed existing coverage with policyholders"],
    [/^Confer with clients to obtain and provide information when claims/i, "Collected information for policy claims"],
    [/^Interview prospective clients to obtain data about their financial resources and needs/i, "Assessed prospective customers' insurance needs"],
    [/^Contact underwriter and submit forms/i, "Submitted coverage forms to underwriters"],
    [/^Select company that offers type of coverage requested by client/i, "Compared insurers to find suitable coverage"],
    [/^Ensure that policy requirements are fulfilled/i, "Verified policy forms and coverage requirements"],
    [/^Develop marketing strategies to compete with other/i, "Developed insurance marketing strategies"],
    [/^Calculate premiums and establish payment method/i, "Calculated premiums and arranged payment methods"],
    [/^Generate standard or custom reports summarizing business, financial, or economic data/i, "Prepared reports summarizing business or financial data"],
    [/^Maintain or update business intelligence tools/i, "Updated reporting dashboards and data sources"],
    [/^Manage timely flow of business intelligence information/i, "Delivered reporting information to users on schedule"],
    [/^Document specifications for business intelligence or information technology reports/i, "Documented report and dashboard requirements"],
    [/^Create business intelligence tools or systems/i, "Built reporting tools and supporting spreadsheets"],
    [/^Greet customers entering establishments/i, "Greeted customers as they arrived"],
    [/^Operate computers programmed with accounting software to record/i, "Recorded accounting information using accounting software"],
    [/^Check figures, postings, and documents for correct entry/i, "Checked accounting entries for accuracy"],
    [/^Perform financial calculations/i, "Calculated financial amounts"],
    [/^Perform general office duties, such as filing/i, "Completed routine office tasks"],
    [/^Receive and count stock items/i, "Received and counted stock items"],
    [/^Receive, unload, open, unpack, or issue sales floor merchandise/i, "Received stock deliveries"],
    [/^Operate telephone switchboard to answer, screen, or forward calls/i, "Answered incoming calls and took messages"],
    [/^Greet persons entering establishment, determine nature and purpose of visit/i, "Greeted visitors and directed them to the right place"],
    [/^Receive payment (?:and record receipts|by cash, check)/i, "Processed payments"],
    [/^Schedule appointments and maintain and update appointment calendars/i, "Scheduled appointments and kept the calendar up to date"],
    [/^Hear and resolve complaints from customers or the public/i, "Resolved customer complaints"],
    [/^File and maintain records/i, "Filed documents and kept records up to date"],
    [/^Transmit information or documents to customers, using computer, mail/i, "Sent documents and information to customers"],
    [/^Provide information about establishment, such as location of departments/i, "Provided visitors with information about services and locations"],
    [/^Perform administrative support tasks, such as proofreading/i, "Checked documents for errors"],
    [/^Collect, sort, distribute, or prepare mail, messages, or courier deliveries/i, "Sorted and distributed mail or deliveries"],
    [/^Perform duties, such as taking care of plants or straightening magazines to maintain lobby or reception area/i, "Maintained a tidy reception area"],
  ];
  return pairs.find(([pattern]) => pattern.test(statement.trim()))?.[1] ?? null;
}
