import { describe, expect, it } from "vitest";
import { changesSince, reviewerScope, threeReviewersPassed } from "./receipt";
import type { ModelReview } from "./model";
const review: ModelReview = { status: "pass", issues: [], model: "synthetic", message: "passed", reviewers: ["facts", "reader", "complete"].map((reviewer) => ({ reviewer, label: reviewer, status: "pass", model: "synthetic", issues: [], disqualified: null })) };
describe("evidence shown by the gate", () => {
  it("requires three different, completed, standing reviewers", () => { expect(threeReviewersPassed(review)).toBe(true); expect(threeReviewersPassed({ ...review, reviewers: review.reviewers!.slice(0, 2) })).toBe(false); expect(threeReviewersPassed({ ...review, reviewers: [review.reviewers![0], review.reviewers![0], review.reviewers![1]] })).toBe(false); expect(threeReviewersPassed({ ...review, status: "error" })).toBe(false); });
  it("counts a replacement only when three standing passes remain", () => { const replaced = { ...review.reviewers![0], status: "fail" as const, disqualified: "Contradicted by confirmed fact" }; const spare = { ...review.reviewers![2], reviewer: "replacement" }; expect(threeReviewersPassed({ ...review, reviewers: [replaced, ...review.reviewers!.slice(1), spare] })).toBe(true); expect(threeReviewersPassed({ ...review, reviewers: [replaced, ...review.reviewers!.slice(1)] })).toBe(false); });
  it("shows each reviewer's actual scope", () => { expect(reviewerScope("facts")).toContain("Truthfulness"); expect(reviewerScope("reader")).toContain("employer"); expect(reviewerScope("complete")).toContain("formatting"); });
  it("shows an observed revision, not the suggested fix", () => { const previous = { documentLines: [{ key: "b1", text: "Led a team of 5" }], model: { ...review, status: "fail" as const, issues: [{ quote: "Led a team of 5", category: "unsupported_claim" as const, rule_broken: "Facts say helped", fix: "Helped a team of 5" }] } }; expect(changesSince(previous, [{ key: "b1", text: "Helped prepare the report" }])).toEqual([{ before: "Led a team of 5", after: "Helped prepare the report", rule: "Facts say helped" }]); expect(changesSince(previous, previous.documentLines)).toEqual([]); expect(changesSince(previous, [])).toEqual([{ before: "Led a team of 5", after: null, rule: "Facts say helped" }]); });
  it("reports deterministic quoted fixes and preserves them after a PASS", () => { const before = { documentLines: [{ key: "b", text: "Built a report\u2014monthly" }], model: { ...review, status: "skipped" as const }, linter: [{ passed: false, evidence_quote: "\u2014", detail: "No em dashes" }] }; const changes = changesSince(before, [{ key: "b", text: "Built a monthly report" }]); expect(changes[0]).toMatchObject({ before: "Built a report\u2014monthly", after: "Built a monthly report" }); expect(changesSince({ ...before, model: review, changes, linter: [] }, [{ key: "b", text: "Built a monthly report" }])).toEqual(changes); });
  it("does not invent changes for an old result without a document snapshot or a nonverbatim quote", () => { expect(changesSince({ model: review }, [])).toEqual([]); expect(changesSince({ documentLines: [{ key: "b", text: "Confirmed line" }], model: { ...review, issues: [{ quote: "Invented quote", category: "other", rule_broken: "Rule", fix: "Suggestion" }] } }, [])).toEqual([]); });
});
