"use client";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { prepareRelationshipAction, sendRelationshipAction } from "@/app/app/tracker/actions";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { MessageKind, RelationshipLane as Lane } from "@/lib/outreach/model";
import { GateReceipt } from "@/components/review/gate-receipt";

export function RelationshipLane({ applicationId, lane, submitted, due, reviewFollowUp = false }: { applicationId: string; lane?: Lane; submitted: boolean; due: boolean; reviewFollowUp?: boolean }) {
  const [why, setWhy] = useState(lane?.why ?? "");
  const [reviewing, setReviewing] = useState<MessageKind | null>(reviewFollowUp && due && lane?.followUpGate?.passed && !lane.sendState && !lane.touches.some((touch) => touch.kind === "follow_up") ? "follow_up" : null);
  const [pending, startTransition] = useTransition();
  const draft = reviewing === "follow_up" ? lane?.followUp : lane?.draft;
  const gate = reviewing === "follow_up" ? lane?.followUpGate : lane?.gate;
  function prepare(kind: MessageKind) {
    startTransition(async () => { try { await prepareRelationshipAction(applicationId, kind, why.trim() || undefined); toast("Contact search and message checks saved."); } catch (error) { toast.error(error instanceof Error ? error.message : "Preparation could not finish."); } });
  }
  return <section className="space-y-3 rounded-xl border p-4">
    <h3 className="text-sm font-semibold">A conversation about this role</h3>
    <p className="text-xs leading-5 text-muted-foreground">One relevant example and your own reason for wanting this job. You review every message before sending.</p>
    {lane && !lane.contact && <p className="text-sm font-medium">No verified contact found</p>}
    {lane?.contact ? <div className="text-sm"><p className="font-medium">{lane.contact.name} · {lane.contact.role}</p><p>{lane.contact.email}</p><a className="text-xs underline" href={lane.contact.sourceUrl} target="_blank" rel="noreferrer">Verify in the posting</a><details className="mt-1 text-xs"><summary>Source evidence</summary><blockquote className="mt-2 whitespace-pre-wrap">{lane.contact.quote}</blockquote><p className="mt-1 text-muted-foreground">Read {new Date(lane.contact.verifiedAt).toLocaleString()}</p></details></div> : <p className="text-xs leading-5 text-muted-foreground">{lane?.emptyReason ?? "Search the live employer posting for a named hiring contact. A name or email will never be guessed."}</p>}
    <label className="block space-y-1 text-xs"><span>In your words, why this role?</span><Textarea value={why} onChange={(e) => setWhy(e.target.value)} maxLength={1200} rows={2} /></label>
    <Button size="sm" variant="outline" disabled={pending || Boolean(lane?.sendState)} onClick={() => prepare("outreach")}>{lane?.gate ? "Prepare outreach again" : "Find contact and check outreach"}</Button>
    {lane?.draft && <div className="space-y-2"><p className="text-xs">Outreach: {lane.gate?.passed ? "PASS. Three reviewers checked the message." : "Needs changes before sending."}</p>{lane.gate?.checks.filter((c) => !c.ok).map((c) => <p key={c.label} className="text-xs text-destructive">{c.label}: {c.detail}</p>)}{lane.gate?.model.issues.map((issue) => <blockquote key={issue.quote} className="text-xs"><p className="whitespace-pre-wrap">“{issue.quote}”</p><p>{issue.rule_broken}</p><p>Suggested fix: {issue.fix}</p></blockquote>)}<Button size="sm" disabled={pending || !lane.gate?.passed || Boolean(lane.sendState) || lane.touches.some((t) => t.kind === "outreach")} onClick={() => setReviewing("outreach")}>Review outreach</Button></div>}
    {submitted && <div className="space-y-2 border-t pt-3"><p className="text-sm font-medium">Day 14 follow-up{due ? " is due" : ""}</p><p className="text-xs text-muted-foreground">{lane?.followUpGate?.passed ? "The draft already passed its checks. It becomes available to send 14 days after submission while you are waiting for a reply." : "Prepare the draft now so its checks are finished when the reminder becomes due."}</p><Button size="sm" variant="outline" disabled={pending || Boolean(lane?.sendState)} onClick={() => prepare("follow_up")}>Prepare and check follow-up</Button>{lane?.followUp && <Button size="sm" disabled={pending || !due || !lane.followUpGate?.passed || Boolean(lane.sendState) || lane.touches.some((t) => t.kind === "follow_up")} onClick={() => setReviewing("follow_up")}>Review due follow-up</Button>}{lane?.followUpGate?.checks.filter((c) => !c.ok).map((c) => <p key={c.label} className="text-xs text-destructive">{c.label}: {c.detail}</p>)}{lane?.followUpGate?.model.issues.map((issue) => <blockquote key={issue.quote} className="text-xs"><p>“{issue.quote}”</p><p>{issue.rule_broken}</p><p>Suggested fix: {issue.fix}</p></blockquote>)}</div>}
    {lane?.sendState && <p role="status" className="text-xs text-muted-foreground">A send is awaiting confirmation. Another send is locked to prevent a duplicate.</p>}
    {lane?.gate && <GateReceipt model={lane.gate.model} passed={lane.gate.passed} changes={lane.gate.changes} />}
    {lane?.followUpGate && <div><p className="mb-2 text-xs font-medium">Follow-up quality gate</p><GateReceipt model={lane.followUpGate.model} passed={lane.followUpGate.passed} changes={lane.followUpGate.changes} /></div>}
    {!!lane?.touches.length && <div className="border-t pt-3"><h4 className="text-sm font-medium">Conversation timeline</h4><ol className="mt-2 space-y-3">{lane.touches.map((touch) => <li key={touch.id} className="text-xs"><p className="font-medium">{touch.kind === "outreach" ? "Outreach" : "Follow-up"} sent · {new Date(touch.at).toLocaleString()}</p><p>To {touch.to}</p><p className="text-muted-foreground">Provider receipt: {touch.providerId}. Accepted for sending; delivery is not yet confirmed.</p><details><summary>{touch.subject}</summary><p className="mt-2 whitespace-pre-wrap leading-5">{touch.body}</p></details></li>)}</ol></div>}
    <Dialog open={Boolean(reviewing)} onOpenChange={(open) => { if (!open) setReviewing(null); }}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>Review before sending</DialogTitle><DialogDescription>To {lane?.contact?.name} at {lane?.contact?.email}. Replies go to your account email.</DialogDescription></DialogHeader><p className="font-medium">{draft?.subject}</p><p className="whitespace-pre-wrap text-sm leading-6">{draft?.body}</p><p className="text-xs text-muted-foreground">This exact draft passed truthfulness, voice, formatting, and employer checks. To change it, close this view and prepare it again.</p><Button disabled={pending || !reviewing || !gate?.passed} onClick={() => { if (!reviewing || !gate) return; const kind = reviewing; startTransition(async () => { try { await sendRelationshipAction(applicationId, kind, gate.fingerprint); setReviewing(null); toast("Email accepted for sending. The provider receipt is saved."); } catch (error) { toast.error(error instanceof Error ? error.message : "No send was confirmed."); } }); }}>Send this reviewed message</Button></DialogContent></Dialog>
  </section>;
}
